"""
Forcast2.py - 5-Day Forecast Runner
-----------------------------------
Maintained for backward compatibility with existing automation workflows.
Note: Forcast.py now automatically produces both 15-day and 5-day forecast images in a single pass.
If Forcast.py has already generated the plots, this script verifies them and exits cleanly without redundant downloads.
"""
import glob
import os
import sys

def main():
    # Check if 5-day forecast plots were already generated by Forcast.py
    existing_5day_plots = glob.glob("public/assets/tropical_cyclone_5day_forecast_*.png")
    if existing_5day_plots:
        print(f"Forcast2.py: Found {len(existing_5day_plots)} 5-day forecast plot(s) already generated by Forcast.py:")
        for p in existing_5day_plots[:3]:
            print(f"  ✓ {p}")
        print("Forcast2.py: Skipping duplicate download pass.")
        return

    print("Forcast2.py: 5-day plots not found. Running Forcast.py to generate both 5-day and 15-day maps...")
    import Forcast
    Forcast.main()

if __name__ == "__main__":
    main()